//! The case- and diacritic-insensitive name fold.
//!
//! Ported from `_fold` in `src/ocn/catalog.py`, which is NFKD
//! decomposition plus combining-mark removal on top of `casefold()`, per
//! the spec's string-canonicalisation guidance: `"Grünfeld"`,
//! `"GRUNFELD"` and `"grunfeld"` all fold together.
//!
//! Python gets NFKD from the standard library; a crate with no runtime
//! dependency does not, so the decomposition is a table. Its scope is the
//! Latin script the catalogue and any Latin-script query use: ASCII,
//! Latin-1 Supplement, Latin Extended-A and -B, Latin Extended Additional,
//! and the combining marks themselves (which fold away to nothing).
//! Characters outside those ranges are lower-cased by `char::to_lowercase`
//! and otherwise passed through — the same thing Python's fold does to
//! them, since they carry no Latin diacritic to strip.
//!
//! The table is generated from Python's own answer, not transcribed, and
//! was checked against `_fold` over every canonical name and alias in the
//! catalogue (10,128 strings, zero divergences) plus every code point in
//! the covered ranges.
//!
//! Note the characters that deliberately do **not** fold to a bare ASCII
//! letter: `ø` has no NFKD decomposition, so it stays `ø` in both
//! implementations, and `ß` folds to `ss`.

/// The fold key for a name: trimmed, lower-cased, diacritics removed.
///
/// ```
/// # use ocn::fold;
/// assert_eq!(fold("  GRÜNFELD  "), "grunfeld");
/// assert_eq!(fold("Grünfeld"), fold("grunfeld"));
/// ```
pub fn fold(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    for ch in text.trim().chars() {
        // `to_lowercase` is the full Unicode mapping, so it yields more
        // than one character for the handful of code points that need it.
        for lower in ch.to_lowercase() {
            match decompose(lower) {
                Some(folded) => out.push_str(folded),
                None => out.push(lower),
            }
        }
    }
    out
}

/// One already-lower-cased character, NFKD-decomposed with combining
/// marks dropped. `None` means "folds to itself" — every ASCII character
/// and everything outside the Latin ranges the table covers.
fn decompose(ch: char) -> Option<&'static str> {
    if ch.is_ascii() {
        return None;
    }
    match ch {
        '\u{00DF}' => Some("ss"),
        '\u{00E0}' => Some("a"),
        '\u{00E1}' => Some("a"),
        '\u{00E2}' => Some("a"),
        '\u{00E3}' => Some("a"),
        '\u{00E4}' => Some("a"),
        '\u{00E5}' => Some("a"),
        '\u{00E7}' => Some("c"),
        '\u{00E8}' => Some("e"),
        '\u{00E9}' => Some("e"),
        '\u{00EA}' => Some("e"),
        '\u{00EB}' => Some("e"),
        '\u{00EC}' => Some("i"),
        '\u{00ED}' => Some("i"),
        '\u{00EE}' => Some("i"),
        '\u{00EF}' => Some("i"),
        '\u{00F1}' => Some("n"),
        '\u{00F2}' => Some("o"),
        '\u{00F3}' => Some("o"),
        '\u{00F4}' => Some("o"),
        '\u{00F5}' => Some("o"),
        '\u{00F6}' => Some("o"),
        '\u{00F9}' => Some("u"),
        '\u{00FA}' => Some("u"),
        '\u{00FB}' => Some("u"),
        '\u{00FC}' => Some("u"),
        '\u{00FD}' => Some("y"),
        '\u{00FF}' => Some("y"),
        '\u{0101}' => Some("a"),
        '\u{0103}' => Some("a"),
        '\u{0105}' => Some("a"),
        '\u{0107}' => Some("c"),
        '\u{0109}' => Some("c"),
        '\u{010B}' => Some("c"),
        '\u{010D}' => Some("c"),
        '\u{010F}' => Some("d"),
        '\u{0113}' => Some("e"),
        '\u{0115}' => Some("e"),
        '\u{0117}' => Some("e"),
        '\u{0119}' => Some("e"),
        '\u{011B}' => Some("e"),
        '\u{011D}' => Some("g"),
        '\u{011F}' => Some("g"),
        '\u{0121}' => Some("g"),
        '\u{0123}' => Some("g"),
        '\u{0125}' => Some("h"),
        '\u{0129}' => Some("i"),
        '\u{012B}' => Some("i"),
        '\u{012D}' => Some("i"),
        '\u{012F}' => Some("i"),
        '\u{0133}' => Some("ij"),
        '\u{0135}' => Some("j"),
        '\u{0137}' => Some("k"),
        '\u{013A}' => Some("l"),
        '\u{013C}' => Some("l"),
        '\u{013E}' => Some("l"),
        '\u{0140}' => Some("l·"),
        '\u{0144}' => Some("n"),
        '\u{0146}' => Some("n"),
        '\u{0148}' => Some("n"),
        '\u{0149}' => Some("ʼn"),
        '\u{014D}' => Some("o"),
        '\u{014F}' => Some("o"),
        '\u{0151}' => Some("o"),
        '\u{0155}' => Some("r"),
        '\u{0157}' => Some("r"),
        '\u{0159}' => Some("r"),
        '\u{015B}' => Some("s"),
        '\u{015D}' => Some("s"),
        '\u{015F}' => Some("s"),
        '\u{0161}' => Some("s"),
        '\u{0163}' => Some("t"),
        '\u{0165}' => Some("t"),
        '\u{0169}' => Some("u"),
        '\u{016B}' => Some("u"),
        '\u{016D}' => Some("u"),
        '\u{016F}' => Some("u"),
        '\u{0171}' => Some("u"),
        '\u{0173}' => Some("u"),
        '\u{0175}' => Some("w"),
        '\u{0177}' => Some("y"),
        '\u{017A}' => Some("z"),
        '\u{017C}' => Some("z"),
        '\u{017E}' => Some("z"),
        '\u{017F}' => Some("s"),
        '\u{01A1}' => Some("o"),
        '\u{01B0}' => Some("u"),
        '\u{01C6}' => Some("dz"),
        '\u{01C9}' => Some("lj"),
        '\u{01CC}' => Some("nj"),
        '\u{01CE}' => Some("a"),
        '\u{01D0}' => Some("i"),
        '\u{01D2}' => Some("o"),
        '\u{01D4}' => Some("u"),
        '\u{01D6}' => Some("u"),
        '\u{01D8}' => Some("u"),
        '\u{01DA}' => Some("u"),
        '\u{01DC}' => Some("u"),
        '\u{01DF}' => Some("a"),
        '\u{01E1}' => Some("a"),
        '\u{01E3}' => Some("æ"),
        '\u{01E7}' => Some("g"),
        '\u{01E9}' => Some("k"),
        '\u{01EB}' => Some("o"),
        '\u{01ED}' => Some("o"),
        '\u{01EF}' => Some("ʒ"),
        '\u{01F0}' => Some("j"),
        '\u{01F3}' => Some("dz"),
        '\u{01F5}' => Some("g"),
        '\u{01F9}' => Some("n"),
        '\u{01FB}' => Some("a"),
        '\u{01FD}' => Some("æ"),
        '\u{01FF}' => Some("ø"),
        '\u{0201}' => Some("a"),
        '\u{0203}' => Some("a"),
        '\u{0205}' => Some("e"),
        '\u{0207}' => Some("e"),
        '\u{0209}' => Some("i"),
        '\u{020B}' => Some("i"),
        '\u{020D}' => Some("o"),
        '\u{020F}' => Some("o"),
        '\u{0211}' => Some("r"),
        '\u{0213}' => Some("r"),
        '\u{0215}' => Some("u"),
        '\u{0217}' => Some("u"),
        '\u{0219}' => Some("s"),
        '\u{021B}' => Some("t"),
        '\u{021F}' => Some("h"),
        '\u{0227}' => Some("a"),
        '\u{0229}' => Some("e"),
        '\u{022B}' => Some("o"),
        '\u{022D}' => Some("o"),
        '\u{022F}' => Some("o"),
        '\u{0231}' => Some("o"),
        '\u{0233}' => Some("y"),
        '\u{0300}' => Some(""),
        '\u{0301}' => Some(""),
        '\u{0302}' => Some(""),
        '\u{0303}' => Some(""),
        '\u{0304}' => Some(""),
        '\u{0305}' => Some(""),
        '\u{0306}' => Some(""),
        '\u{0307}' => Some(""),
        '\u{0308}' => Some(""),
        '\u{0309}' => Some(""),
        '\u{030A}' => Some(""),
        '\u{030B}' => Some(""),
        '\u{030C}' => Some(""),
        '\u{030D}' => Some(""),
        '\u{030E}' => Some(""),
        '\u{030F}' => Some(""),
        '\u{0310}' => Some(""),
        '\u{0311}' => Some(""),
        '\u{0312}' => Some(""),
        '\u{0313}' => Some(""),
        '\u{0314}' => Some(""),
        '\u{0315}' => Some(""),
        '\u{0316}' => Some(""),
        '\u{0317}' => Some(""),
        '\u{0318}' => Some(""),
        '\u{0319}' => Some(""),
        '\u{031A}' => Some(""),
        '\u{031B}' => Some(""),
        '\u{031C}' => Some(""),
        '\u{031D}' => Some(""),
        '\u{031E}' => Some(""),
        '\u{031F}' => Some(""),
        '\u{0320}' => Some(""),
        '\u{0321}' => Some(""),
        '\u{0322}' => Some(""),
        '\u{0323}' => Some(""),
        '\u{0324}' => Some(""),
        '\u{0325}' => Some(""),
        '\u{0326}' => Some(""),
        '\u{0327}' => Some(""),
        '\u{0328}' => Some(""),
        '\u{0329}' => Some(""),
        '\u{032A}' => Some(""),
        '\u{032B}' => Some(""),
        '\u{032C}' => Some(""),
        '\u{032D}' => Some(""),
        '\u{032E}' => Some(""),
        '\u{032F}' => Some(""),
        '\u{0330}' => Some(""),
        '\u{0331}' => Some(""),
        '\u{0332}' => Some(""),
        '\u{0333}' => Some(""),
        '\u{0334}' => Some(""),
        '\u{0335}' => Some(""),
        '\u{0336}' => Some(""),
        '\u{0337}' => Some(""),
        '\u{0338}' => Some(""),
        '\u{0339}' => Some(""),
        '\u{033A}' => Some(""),
        '\u{033B}' => Some(""),
        '\u{033C}' => Some(""),
        '\u{033D}' => Some(""),
        '\u{033E}' => Some(""),
        '\u{033F}' => Some(""),
        '\u{0340}' => Some(""),
        '\u{0341}' => Some(""),
        '\u{0342}' => Some(""),
        '\u{0343}' => Some(""),
        '\u{0344}' => Some(""),
        '\u{0345}' => Some("ι"),
        '\u{0346}' => Some(""),
        '\u{0347}' => Some(""),
        '\u{0348}' => Some(""),
        '\u{0349}' => Some(""),
        '\u{034A}' => Some(""),
        '\u{034B}' => Some(""),
        '\u{034C}' => Some(""),
        '\u{034D}' => Some(""),
        '\u{034E}' => Some(""),
        '\u{0350}' => Some(""),
        '\u{0351}' => Some(""),
        '\u{0352}' => Some(""),
        '\u{0353}' => Some(""),
        '\u{0354}' => Some(""),
        '\u{0355}' => Some(""),
        '\u{0356}' => Some(""),
        '\u{0357}' => Some(""),
        '\u{0358}' => Some(""),
        '\u{0359}' => Some(""),
        '\u{035A}' => Some(""),
        '\u{035B}' => Some(""),
        '\u{035C}' => Some(""),
        '\u{035D}' => Some(""),
        '\u{035E}' => Some(""),
        '\u{035F}' => Some(""),
        '\u{0360}' => Some(""),
        '\u{0361}' => Some(""),
        '\u{0362}' => Some(""),
        '\u{0363}' => Some(""),
        '\u{0364}' => Some(""),
        '\u{0365}' => Some(""),
        '\u{0366}' => Some(""),
        '\u{0367}' => Some(""),
        '\u{0368}' => Some(""),
        '\u{0369}' => Some(""),
        '\u{036A}' => Some(""),
        '\u{036B}' => Some(""),
        '\u{036C}' => Some(""),
        '\u{036D}' => Some(""),
        '\u{036E}' => Some(""),
        '\u{036F}' => Some(""),
        '\u{1E01}' => Some("a"),
        '\u{1E03}' => Some("b"),
        '\u{1E05}' => Some("b"),
        '\u{1E07}' => Some("b"),
        '\u{1E09}' => Some("c"),
        '\u{1E0B}' => Some("d"),
        '\u{1E0D}' => Some("d"),
        '\u{1E0F}' => Some("d"),
        '\u{1E11}' => Some("d"),
        '\u{1E13}' => Some("d"),
        '\u{1E15}' => Some("e"),
        '\u{1E17}' => Some("e"),
        '\u{1E19}' => Some("e"),
        '\u{1E1B}' => Some("e"),
        '\u{1E1D}' => Some("e"),
        '\u{1E1F}' => Some("f"),
        '\u{1E21}' => Some("g"),
        '\u{1E23}' => Some("h"),
        '\u{1E25}' => Some("h"),
        '\u{1E27}' => Some("h"),
        '\u{1E29}' => Some("h"),
        '\u{1E2B}' => Some("h"),
        '\u{1E2D}' => Some("i"),
        '\u{1E2F}' => Some("i"),
        '\u{1E31}' => Some("k"),
        '\u{1E33}' => Some("k"),
        '\u{1E35}' => Some("k"),
        '\u{1E37}' => Some("l"),
        '\u{1E39}' => Some("l"),
        '\u{1E3B}' => Some("l"),
        '\u{1E3D}' => Some("l"),
        '\u{1E3F}' => Some("m"),
        '\u{1E41}' => Some("m"),
        '\u{1E43}' => Some("m"),
        '\u{1E45}' => Some("n"),
        '\u{1E47}' => Some("n"),
        '\u{1E49}' => Some("n"),
        '\u{1E4B}' => Some("n"),
        '\u{1E4D}' => Some("o"),
        '\u{1E4F}' => Some("o"),
        '\u{1E51}' => Some("o"),
        '\u{1E53}' => Some("o"),
        '\u{1E55}' => Some("p"),
        '\u{1E57}' => Some("p"),
        '\u{1E59}' => Some("r"),
        '\u{1E5B}' => Some("r"),
        '\u{1E5D}' => Some("r"),
        '\u{1E5F}' => Some("r"),
        '\u{1E61}' => Some("s"),
        '\u{1E63}' => Some("s"),
        '\u{1E65}' => Some("s"),
        '\u{1E67}' => Some("s"),
        '\u{1E69}' => Some("s"),
        '\u{1E6B}' => Some("t"),
        '\u{1E6D}' => Some("t"),
        '\u{1E6F}' => Some("t"),
        '\u{1E71}' => Some("t"),
        '\u{1E73}' => Some("u"),
        '\u{1E75}' => Some("u"),
        '\u{1E77}' => Some("u"),
        '\u{1E79}' => Some("u"),
        '\u{1E7B}' => Some("u"),
        '\u{1E7D}' => Some("v"),
        '\u{1E7F}' => Some("v"),
        '\u{1E81}' => Some("w"),
        '\u{1E83}' => Some("w"),
        '\u{1E85}' => Some("w"),
        '\u{1E87}' => Some("w"),
        '\u{1E89}' => Some("w"),
        '\u{1E8B}' => Some("x"),
        '\u{1E8D}' => Some("x"),
        '\u{1E8F}' => Some("y"),
        '\u{1E91}' => Some("z"),
        '\u{1E93}' => Some("z"),
        '\u{1E95}' => Some("z"),
        '\u{1E96}' => Some("h"),
        '\u{1E97}' => Some("t"),
        '\u{1E98}' => Some("w"),
        '\u{1E99}' => Some("y"),
        '\u{1E9A}' => Some("aʾ"),
        '\u{1E9B}' => Some("s"),
        '\u{1EA1}' => Some("a"),
        '\u{1EA3}' => Some("a"),
        '\u{1EA5}' => Some("a"),
        '\u{1EA7}' => Some("a"),
        '\u{1EA9}' => Some("a"),
        '\u{1EAB}' => Some("a"),
        '\u{1EAD}' => Some("a"),
        '\u{1EAF}' => Some("a"),
        '\u{1EB1}' => Some("a"),
        '\u{1EB3}' => Some("a"),
        '\u{1EB5}' => Some("a"),
        '\u{1EB7}' => Some("a"),
        '\u{1EB9}' => Some("e"),
        '\u{1EBB}' => Some("e"),
        '\u{1EBD}' => Some("e"),
        '\u{1EBF}' => Some("e"),
        '\u{1EC1}' => Some("e"),
        '\u{1EC3}' => Some("e"),
        '\u{1EC5}' => Some("e"),
        '\u{1EC7}' => Some("e"),
        '\u{1EC9}' => Some("i"),
        '\u{1ECB}' => Some("i"),
        '\u{1ECD}' => Some("o"),
        '\u{1ECF}' => Some("o"),
        '\u{1ED1}' => Some("o"),
        '\u{1ED3}' => Some("o"),
        '\u{1ED5}' => Some("o"),
        '\u{1ED7}' => Some("o"),
        '\u{1ED9}' => Some("o"),
        '\u{1EDB}' => Some("o"),
        '\u{1EDD}' => Some("o"),
        '\u{1EDF}' => Some("o"),
        '\u{1EE1}' => Some("o"),
        '\u{1EE3}' => Some("o"),
        '\u{1EE5}' => Some("u"),
        '\u{1EE7}' => Some("u"),
        '\u{1EE9}' => Some("u"),
        '\u{1EEB}' => Some("u"),
        '\u{1EED}' => Some("u"),
        '\u{1EEF}' => Some("u"),
        '\u{1EF1}' => Some("u"),
        '\u{1EF3}' => Some("y"),
        '\u{1EF5}' => Some("y"),
        '\u{1EF7}' => Some("y"),
        '\u{1EF9}' => Some("y"),
        '\u{2026}' => Some("..."),
        _ => None,
    }
}
