#!/usr/bin/env python3
"""Sync the catalogue into the published packages' bundled data.

Both packages ship the catalogue inside the artefact (the tzdata model):
`pip install ocn-chess` and `cargo add ocn` must answer lookups on a
machine with no checkout and no network. That means `src/ocn/data/` and
`rust/data/` hold committed copies of catalogue artefacts, and copies
drift. This script is the one way to refresh them, and
`tests/test_package_data.py` fails the suite whenever the committed bytes
stop matching a fresh run — for either target.

    python3 tools/sync_package_data.py            # dry run, report drift
    python3 tools/sync_package_data.py --apply    # rewrite both data dirs

What lands in `src/ocn/data/`:

- `ocn-1.csv`             copied verbatim from `catalog/`.
- `ocn-1.lichess-xref.tsv` copied verbatim from `catalog/`.
- `ocn-1.positions.tsv`   generated by `export_positions.py` (the
                          position index `Catalog.by_fen` reads).
- `VERSION`               the catalogue release the data came from.

`rust/data/` takes the same bytes minus the Lichess cross-reference,
which the crate has no reader for; adding it would grow every compiled
binary by 436 KB for nothing. One payload, one drift guard, two targets:
the two packages can never ship different catalogues under the same
version number.
"""
from __future__ import annotations

import argparse
import io
import sys
from pathlib import Path

try:
    from export_positions import derive_rows, load_catalog, write_tsv
except ImportError:  # pragma: no cover - only for unusual direct imports.
    from tools.export_positions import derive_rows, load_catalog, write_tsv


REPO_ROOT = Path(__file__).resolve().parent.parent
CATALOG_DIR = REPO_ROOT / "catalog"
DATA_DIR = REPO_ROOT / "src" / "ocn" / "data"
RUST_DATA_DIR = REPO_ROOT / "rust" / "data"

# The catalogue release the bundled data represents. Bump on release;
# the package's own `__version__` (src/ocn/__init__.py) tracks the reader
# and moves independently.
CATALOG_VERSION = "1.2.1"

COPIED = ("ocn-1.csv", "ocn-1.lichess-xref.tsv")
POSITIONS = "ocn-1.positions.tsv"
VERSION = "VERSION"

#: What the Rust crate embeds: everything the reader has code for. The
#: Lichess cross-reference is deliberately absent (see the module
#: docstring).
RUST_FILES = ("ocn-1.csv", POSITIONS, VERSION)


def build_positions_tsv(catalog_path: Path) -> str:
    """Render the positions index exactly as `export_positions.py` would."""
    rows = derive_rows(load_catalog(catalog_path), include_roots=False)
    buffer = io.StringIO()
    write_tsv(rows, buffer)
    return buffer.getvalue()


def build_payload(catalog_dir: Path = CATALOG_DIR) -> dict[str, str]:
    """Return `{filename: exact text}` for everything under `src/ocn/data/`."""
    payload = {
        name: (catalog_dir / name).read_text(encoding="utf-8") for name in COPIED
    }
    payload[POSITIONS] = build_positions_tsv(catalog_dir / "ocn-1.csv")
    payload[VERSION] = CATALOG_VERSION + "\n"
    return payload


def rust_payload(payload: dict[str, str] | None = None) -> dict[str, str]:
    """The subset of `build_payload()` the Rust crate embeds.

    Derived from the same payload rather than rebuilt, so the two targets
    cannot diverge even in principle.
    """
    payload = build_payload() if payload is None else payload
    return {name: payload[name] for name in RUST_FILES}


def drifted(payload: dict[str, str], data_dir: Path = DATA_DIR) -> list[str]:
    """Names whose committed bytes differ from a fresh build (missing counts)."""
    stale: list[str] = []
    for name, text in payload.items():
        path = data_dir / name
        if not path.exists() or path.read_text(encoding="utf-8") != text:
            stale.append(name)
    return sorted(stale)


def write_payload(payload: dict[str, str], data_dir: Path = DATA_DIR) -> None:
    data_dir.mkdir(parents=True, exist_ok=True)
    for name, text in payload.items():
        (data_dir / name).write_text(text, encoding="utf-8")


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Sync catalog/ artefacts into the ocn-chess package data."
    )
    parser.add_argument(
        "--apply",
        action="store_true",
        help="write the files (default: report drift and change nothing)",
    )
    parser.add_argument("--catalog-dir", type=Path, default=CATALOG_DIR)
    parser.add_argument("--data-dir", type=Path, default=DATA_DIR)
    parser.add_argument("--rust-data-dir", type=Path, default=RUST_DATA_DIR)
    return parser.parse_args(argv)


def shown(directory: Path, name: str) -> str:
    """The path as a reader can use it — `git add` has to accept this."""
    path = (directory / name).resolve()
    try:
        return str(path.relative_to(Path.cwd()))
    except ValueError:
        return str(path)


def main() -> int:
    args = parse_args(sys.argv[1:])
    payload = build_payload(args.catalog_dir)
    targets = [
        (args.data_dir, payload),
        (args.rust_data_dir, rust_payload(payload)),
    ]

    stale = [
        (directory, target, drifted(target, directory))
        for directory, target in targets
    ]
    total = sum(len(names) for *_, names in stale)
    files = sum(len(target) for _, target in targets)

    if not total:
        print(f"OK bundled data is current ({files} files, 2 targets)")
        return 0

    if not args.apply:
        for directory, _, names in stale:
            for name in names:
                print(f"DRIFT {shown(directory, name)}")
        print(f"{total} file(s) stale — rerun with --apply", file=sys.stderr)
        return 1

    for directory, target, names in stale:
        if not names:
            continue
        write_payload(target, directory)
        for name in names:
            print(f"WROTE {shown(directory, name)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
