#!/usr/bin/env python3
"""Sync the catalogue into the `ocn-chess` package's bundled data.

The installable package ships the catalogue inside the wheel (the tzdata
model): `pip install ocn-chess` must answer lookups on a machine with no
checkout and no network. That means `src/ocn/data/` holds committed
copies of catalogue artefacts, and copies drift. This script is the one
way to refresh them, and `tests/test_package_data.py` fails the suite
whenever the committed bytes stop matching a fresh run.

    python3 tools/sync_package_data.py            # dry run, report drift
    python3 tools/sync_package_data.py --apply    # rewrite src/ocn/data/

What lands there:

- `ocn-1.csv`             copied verbatim from `catalog/`.
- `ocn-1.lichess-xref.tsv` copied verbatim from `catalog/`.
- `ocn-1.positions.tsv`   generated by `export_positions.py` (the
                          position index `Catalog.by_fen` reads).
- `VERSION`               the catalogue release the data came from.
"""
from __future__ import annotations

import argparse
import io
import sys
from pathlib import Path

try:
    from export_positions import derive_rows, load_catalog, write_tsv
except ImportError:  # pragma: no cover - only for unusual direct imports.
    from tools.export_positions import derive_rows, load_catalog, write_tsv


REPO_ROOT = Path(__file__).resolve().parent.parent
CATALOG_DIR = REPO_ROOT / "catalog"
DATA_DIR = REPO_ROOT / "src" / "ocn" / "data"

# The catalogue release the bundled data represents. Bump on release;
# the package's own `__version__` (src/ocn/__init__.py) tracks the reader
# and moves independently.
CATALOG_VERSION = "1.2.1"

COPIED = ("ocn-1.csv", "ocn-1.lichess-xref.tsv")
POSITIONS = "ocn-1.positions.tsv"
VERSION = "VERSION"


def build_positions_tsv(catalog_path: Path) -> str:
    """Render the positions index exactly as `export_positions.py` would."""
    rows = derive_rows(load_catalog(catalog_path), include_roots=False)
    buffer = io.StringIO()
    write_tsv(rows, buffer)
    return buffer.getvalue()


def build_payload(catalog_dir: Path = CATALOG_DIR) -> dict[str, str]:
    """Return `{filename: exact text}` for everything under `src/ocn/data/`."""
    payload = {
        name: (catalog_dir / name).read_text(encoding="utf-8") for name in COPIED
    }
    payload[POSITIONS] = build_positions_tsv(catalog_dir / "ocn-1.csv")
    payload[VERSION] = CATALOG_VERSION + "\n"
    return payload


def drifted(payload: dict[str, str], data_dir: Path = DATA_DIR) -> list[str]:
    """Names whose committed bytes differ from a fresh build (missing counts)."""
    stale: list[str] = []
    for name, text in payload.items():
        path = data_dir / name
        if not path.exists() or path.read_text(encoding="utf-8") != text:
            stale.append(name)
    return sorted(stale)


def write_payload(payload: dict[str, str], data_dir: Path = DATA_DIR) -> None:
    data_dir.mkdir(parents=True, exist_ok=True)
    for name, text in payload.items():
        (data_dir / name).write_text(text, encoding="utf-8")


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Sync catalog/ artefacts into the ocn-chess package data."
    )
    parser.add_argument(
        "--apply",
        action="store_true",
        help="write the files (default: report drift and change nothing)",
    )
    parser.add_argument("--catalog-dir", type=Path, default=CATALOG_DIR)
    parser.add_argument("--data-dir", type=Path, default=DATA_DIR)
    return parser.parse_args(argv)


def main() -> int:
    args = parse_args(sys.argv[1:])
    payload = build_payload(args.catalog_dir)
    stale = drifted(payload, args.data_dir)

    if not stale:
        print(f"OK bundled data is current ({len(payload)} files)")
        return 0

    if not args.apply:
        for name in stale:
            print(f"DRIFT {name}")
        print(
            f"{len(stale)} file(s) stale — rerun with --apply",
            file=sys.stderr,
        )
        return 1

    write_payload(payload, args.data_dir)
    for name in stale:
        print(f"WROTE {name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
